# Generated by Django 5.1.4 on 2025-09-17 19:11

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('document_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('drivers_license', "Driver's License"), ('national_id', 'National ID Card'), ('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement')], max_length=20, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to=app.models.kyc_document_upload_path)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Verification',
                'verbose_name_plural': 'KYC Verifications',
            },
        ),
    ]
