# Generated by Django 5.1.4 on 2025-09-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_deposittransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('support_ticket', 'Support Ticket'), ('support_reply', 'Support Reply'), ('kyc_update', 'KYC Update'), ('account_update', 'Account Update'), ('deposit_confirmed', 'Deposit Confirmed'), ('general', 'General'), ('system', 'System')], max_length=20),
        ),
    ]
