# Generated by Django 5.1.4 on 2025-09-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_deposittransaction_status_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposittransaction',
            name='completed_at',
        ),
    ]
