# Generated by Django 5.1.4 on 2025-09-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_deposittransaction_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposittransaction',
            name='transaction_hash',
        ),
    ]
