# Generated by Django 5.1.4 on 2025-09-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_deposittransaction_transaction_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='cardano_balance',
            new_name='ripple_balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='polygon_balance',
        ),
        migrations.AddField(
            model_name='wallet',
            name='bnb_tiger_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='stellar_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='coin_type',
            field=models.CharField(choices=[('bitcoin', 'Bitcoin (BTC)'), ('ethereum', 'Ethereum (ETH)'), ('ripple', 'Ripple (XRP)'), ('stellar', 'Stellar (XLM)'), ('usdt', 'Tether (USDT)'), ('bnb', 'BNB (BNB)'), ('bnb_tiger', 'BNB Tiger')], max_length=20),
        ),
    ]
