# Generated by Django 5.1.4 on 2025-09-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_cardano_balance_wallet_ripple_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposittransaction',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
