# Generated by Django 5.1.4 on 2025-09-23 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_deposittransaction_email_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletCopyTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_type', models.CharField(choices=[('bitcoin', 'Bitcoin (BTC)'), ('ethereum', 'Ethereum (ETH)'), ('ripple', 'Ripple (XRP)'), ('stellar', 'Stellar (XLM)'), ('usdt', 'Tether (USDT)'), ('bnb', 'BNB (BNB)'), ('bnb_tiger', 'BNB Tiger')], max_length=20)),
                ('wallet_address', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('copied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_copy_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet Copy Event',
                'verbose_name_plural': 'Wallet Copy Events',
                'ordering': ['-copied_at'],
            },
        ),
    ]
