# Generated by Django 5.1.4 on 2025-09-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_walletcopytracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deposit amount in USD', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bitcoin_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bitcoin balance in USD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bnb_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='BNB balance in USD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bnb_tiger_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='BNB Tiger balance in USD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='ethereum_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ethereum balance in USD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='ripple_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ripple balance in USD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='stellar_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stellar balance in USD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='usdt_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='USDT balance in USD', max_digits=15),
        ),
    ]
